import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import NextAuthProvider from "@/lib/auth/Provider";
import Navbar from "@/components/Navbar";
import TrpcProvider from "@/lib/trpc/Provider";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import { Session, getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth/utils";
import { Novu } from "@novu/node";

<meta
  name="format-detection"
  content="telephone=no, date=no, email=no, address=no"
/>;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = (await getServerSession(authOptions)) as Session;
  if (session) {
    const novu = new Novu(process.env.NOVU_SECRET_API_KEY as string);

    await novu.subscribers.identify(session?.user?.id, {
      firstName: session?.user?.name as string,
      email: session?.user?.email as string,
    });
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <NextAuthProvider>
            <TrpcProvider>
              <main className="max-w-sm mx-auto py-4">
                <Navbar></Navbar>
                {children}
              </main>
            </TrpcProvider>
          </NextAuthProvider>

          <Toaster />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
